export const dummyData = [
  {
    id: 1,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#1234",
    restAnnual: 23,
    workDay: 10,
  },
  {
    id: 2,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 3,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 4,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 5,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 6,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 7,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 8,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 9,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 10,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 11,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#1234",
    restAnnual: 23,
    workDay: 10,
  },
  {
    id: 12,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 13,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 14,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 15,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 16,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 17,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 18,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 19,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 20,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 21,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#1234",
    restAnnual: 23,
    workDay: 10,
  },
  {
    id: 22,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 23,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 24,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 25,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 26,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 27,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 28,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 29,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 30,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 31,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#1234",
    restAnnual: 23,
    workDay: 10,
  },
  {
    id: 32,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 33,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 34,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 35,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 36,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 37,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 38,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 39,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 40,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 41,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#1234",
    restAnnual: 23,
    workDay: 10,
  },
  {
    id: 42,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 43,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 44,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 45,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 46,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 47,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 48,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 49,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
  {
    id: 50,
    name: "아무개",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 20,
    workDay: 9,
  },
];

export const dummyData2 = {
    statusCode: 200,
    data: [
      {
        annualId: 21,
        name: 'whatever 1',
        employeeNumber: '#1234',
        date: '2023-08-30',
        status: 'UNAPPROVED',
      },
      {
        annualId: 22,
        name: 'whatever 2',
        employeeNumber: '#5678',
        date: '2023-08-30',
        status: 'CANCELED',
      },
      {
        annualId: 23,
        name: 'whatever 3',
        employeeNumber: '#9876',
        date: '2023-08-31',
        status: 'CANCELED',
      },
      {
        annualId: 24,
        name: 'whatever 4',
        employeeNumber: '#5432',
        date: '2023-09-01',
        status: 'UNAPPROVED',
      },
      {
        annualId: 25,
        name: 'whatever 5',
        employeeNumber: '#1357',
        date: '2023-09-02',
        status: 'UNAPPROVED',
      },
      {
        annualId: 26,
        name: 'whatever 6',
        employeeNumber: '#2468',
        date: '2023-09-03',
        status: 'UNAPPROVED',
      },
      {
        annualId: 27,
        name: 'whatever 7',
        employeeNumber: '#9876',
        date: '2023-09-04',
        status: 'CANCELED',
      },
      {
        annualId: 28,
        name: 'whatever 8',
        employeeNumber: '#5432',
        date: '2023-09-05',
        status: 'UNAPPROVED',
      },
      {
        annualId: 29,
        name: 'whatever 9',
        employeeNumber: '#1357',
        date: '2023-09-06',
        status: 'UNAPPROVED',
      },
      {
        annualId: 30,
        name: 'whatever 10',
        employeeNumber: '#2468',
        date: '2023-09-07',
        status: 'CANCELED',
      },
      {
        annualId: 40,
        name: 'whatever 20',
        employeeNumber: '#2468',
        date: '2023-09-15',
        status: 'CANCELED',
      },
      {
        annualId: 41,
        name: 'whatever 1',
        employeeNumber: '#1234',
        date: '2023-08-30',
        status: 'UNAPPROVED',
      },
      {
        annualId: 42,
        name: 'whatever 2',
        employeeNumber: '#5678',
        date: '2023-08-30',
        status: 'CANCELED',
      },
      {
        annualId: 43,
        name: 'whatever 3',
        employeeNumber: '#9876',
        date: '2023-08-31',
        status: 'CANCELED',
      },
      {
        annualId: 44,
        name: 'whatever 4',
        employeeNumber: '#5432',
        date: '2023-09-01',
        status: 'UNAPPROVED',
      },
      {
        annualId: 45,
        name: 'whatever 5',
        employeeNumber: '#1357',
        date: '2023-09-02',
        status: 'CANCELED',
      },
      {
        annualId: 46,
        name: 'whatever 6',
        employeeNumber: '#2468',
        date: '2023-09-03',
        status: 'UNAPPROVED',
      },
      {
        annualId: 47,
        name: 'whatever 7',
        employeeNumber: '#9876',
        date: '2023-09-04',
        status: 'CANCELED',
      },
      {
        annualId: 48,
        name: 'whatever 8',
        employeeNumber: '#5432',
        date: '2023-09-05',
        status: 'CANCELED',
      },
      {
        annualId: 49,
        name: 'whatever 9',
        employeeNumber: '#1357',
        date: '2023-09-06',
        status: 'UNAPPROVED',
      },
      {
        annualId: 50,
        name: 'whatever 10',
        employeeNumber: '#2468',
        date: '2023-09-07',
        status: 'UNAPPROVED',
      },
    ],
  };
  