export const dummyData = [
  {
    id: 1,
    name: "김서연",
    email: "neo@zillinks.com",
    employeeNumber: "#1234",
    restAnnual: 0,
    workDay: 0,
  },
  {
    id: 2,
    name: "이예진",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 1,
    workDay: 1,
  },
  {
    id: 3,
    name: "박지민",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 2,
    workDay: 2,
  },
  {
    id: 4,
    name: "정유나",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 3,
    workDay: 3,
  },
  {
    id: 5,
    name: "장세영",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 4,
    workDay: 4,
  },
  {
    id: 6,
    name: "황정민",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 5,
    workDay: 5,
  },
  {
    id: 7,
    name: "최하은",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 6,
    workDay: 6,
  },
  {
    id: 8,
    name: "이세은",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 7,
    workDay: 7,
  },
  {
    id: 9,
    name: "강현우",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 8,
    workDay: 8,
  },
  {
    id: 10,
    name: "윤주아",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 9,
    workDay: 9,
  },
  {
    id: 11,
    name: "백도현",
    email: "neo@zillinks.com",
    employeeNumber: "#1234",
    restAnnual: 10,
    workDay: 10,
  },
  {
    id: 12,
    name: "민아영",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 11,
    workDay: 11,
  },
  {
    id: 13,
    name: "장승민",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 12,
    workDay: 12,
  },
  {
    id: 14,
    name: "송준우",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 13,
    workDay: 13,
  },
  {
    id: 15,
    name: "김지원",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 14,
    workDay: 14,
  },
  {
    id: 16,
    name: "이예준",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 15,
    workDay: 15,
  },
  {
    id: 17,
    name: "정민서",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 1,
    workDay: 14,
  },
  {
    id: 18,
    name: "강성현",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 2,
    workDay: 13,
  },
  {
    id: 19,
    name: "박윤태",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 3,
    workDay: 12,
  },
  {
    id: 20,
    name: "윤다영",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 4,
    workDay: 11,
  },
  {
    id: 21,
    name: "한은솔",
    email: "neo@zillinks.com",
    employeeNumber: "#1234",
    restAnnual: 5,
    workDay: 10,
  },
  {
    id: 22,
    name: "권태영",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 6,
    workDay: 9,
  },
  {
    id: 23,
    name: "강서윤",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 7,
    workDay: 8,
  },
  {
    id: 24,
    name: "조서진",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 8,
    workDay: 7,
  },
  {
    id: 25,
    name: "이강희",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 9,
    workDay: 6,
  },
  {
    id: 26,
    name: "정도윤",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 10,
    workDay: 5,
  },
  {
    id: 27,
    name: "최민하",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 11,
    workDay: 4,
  },
  {
    id: 28,
    name: "구병민",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 12,
    workDay: 3,
  },
  {
    id: 29,
    name: "임수민",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 13,
    workDay: 2,
  },
  {
    id: 30,
    name: "한민혁",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 14,
    workDay: 1,
  },
  {
    id: 31,
    name: "한정원",
    email: "neo@zillinks.com",
    employeeNumber: "#1234",
    restAnnual: 15,
    workDay: 0,
  },
  {
    id: 32,
    name: "오승현",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 14,
    workDay: 1,
  },
  {
    id: 33,
    name: "박승민",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 13,
    workDay: 2,
  },
  {
    id: 34,
    name: "김수빈",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 12,
    workDay: 3,
  },
  {
    id: 35,
    name: "윤가희",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 11,
    workDay: 4,
  },
  {
    id: 36,
    name: "정은비",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 10,
    workDay: 5,
  },
  {
    id: 37,
    name: "이정하",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 9,
    workDay: 6,
  },
  {
    id: 38,
    name: "임주은",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 8,
    workDay: 7,
  },
  {
    id: 39,
    name: "김태윤",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 7,
    workDay: 8,
  },
  {
    id: 40,
    name: "황민준",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 6,
    workDay: 9,
  },
  {
    id: 41,
    name: "정수진",
    email: "neo@zillinks.com",
    employeeNumber: "#1234",
    restAnnual: 5,
    workDay: 10,
  },
  {
    id: 42,
    name: "송세윤",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 4,
    workDay: 11,
  },
  {
    id: 43,
    name: "박지수",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 3,
    workDay: 12,
  },
  {
    id: 44,
    name: "김도연",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 2,
    workDay: 13,
  },
  {
    id: 45,
    name: "윤서원",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 1,
    workDay: 14,
  },
  {
    id: 46,
    name: "이지민",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 0,
    workDay: 15,
  },
  {
    id: 47,
    name: "최은지",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 1,
    workDay: 14,
  },
  {
    id: 48,
    name: "강수현",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 2,
    workDay: 13,
  },
  {
    id: 49,
    name: "문도희",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 3,
    workDay: 12,
  },
  {
    id: 50,
    name: "조예은",
    email: "neo@zillinks.com",
    employeeNumber: "#5678",
    restAnnual: 2,
    workDay: 11,
  },
];

export const dummyData2 = {
    statusCode: 200,
    data: [
      {
        annualId: 21,
        name: '조예은',
        employeeNumber: '#1234',
        date: '2023-08-30',
        status: 'UNAPPROVED',
      },
      {
        annualId: 22,
        name: '문도희',
        employeeNumber: '#5678',
        date: '2023-08-30',
        status: 'CANCELED',
      },
      {
        annualId: 23,
        name: '김수형',
        employeeNumber: '#9876',
        date: '2023-08-31',
        status: 'CANCELED',
      },
      {
        annualId: 24,
        name: '이지훈',
        employeeNumber: '#5432',
        date: '2023-09-01',
        status: 'UNAPPROVED',
      },
      {
        annualId: 25,
        name: '박세진',
        employeeNumber: '#1357',
        date: '2023-09-02',
        status: 'UNAPPROVED',
      },
      {
        annualId: 26,
        name: '최유리',
        employeeNumber: '#2468',
        date: '2023-09-03',
        status: 'UNAPPROVED',
      },
      {
        annualId: 27,
        name: '정태원',
        employeeNumber: '#9876',
        date: '2023-09-04',
        status: 'CANCELED',
      },
      {
        annualId: 28,
        name: '송민서',
        employeeNumber: '#5432',
        date: '2023-09-05',
        status: 'UNAPPROVED',
      },
      {
        annualId: 29,
        name: '윤상민',
        employeeNumber: '#1357',
        date: '2023-09-06',
        status: 'UNAPPROVED',
      },
      {
        annualId: 30,
        name: '황아름',
        employeeNumber: '#2468',
        date: '2023-09-07',
        status: 'CANCELED',
      },
      {
        annualId: 40,
        name: '조하람',
        employeeNumber: '#2468',
        date: '2023-09-15',
        status: 'CANCELED',
      },
      {
        annualId: 41,
        name: '박승우',
        employeeNumber: '#1234',
        date: '2023-08-30',
        status: 'UNAPPROVED',
      },
      {
        annualId: 42,
        name: '남주원',
        employeeNumber: '#5678',
        date: '2023-08-30',
        status: 'CANCELED',
      },
      {
        annualId: 43,
        name: '조시우',
        employeeNumber: '#9876',
        date: '2023-08-31',
        status: 'CANCELED',
      },
      {
        annualId: 44,
        name: '이하윤',
        employeeNumber: '#5432',
        date: '2023-09-01',
        status: 'UNAPPROVED',
      },
      {
        annualId: 45,
        name: '김영재',
        employeeNumber: '#1357',
        date: '2023-09-02',
        status: 'CANCELED',
      },
      {
        annualId: 46,
        name: '손예림',
        employeeNumber: '#2468',
        date: '2023-09-03',
        status: 'UNAPPROVED',
      },
      {
        annualId: 47,
        name: '이승환',
        employeeNumber: '#9876',
        date: '2023-09-04',
        status: 'CANCELED',
      },
      {
        annualId: 48,
        name: '이서진',
        employeeNumber: '#5432',
        date: '2023-09-05',
        status: 'CANCELED',
      },
      {
        annualId: 49,
        name: '박지윤',
        employeeNumber: '#1357',
        date: '2023-09-06',
        status: 'UNAPPROVED',
      },
      {
        annualId: 50,
        name: '김인영',
        employeeNumber: '#2468',
        date: '2023-09-07',
        status: 'UNAPPROVED',
      },
    ],
  };
  